(* Generated by Mirari (Fri, 6 Dec 2013 01:57:15 GMT). *)

open Ocamlbuild_pack;;
open Ocamlbuild_plugin;;
open Ocaml_compiler;;

let native_link_gen linker =
  link_gen "cmx" "cmxa" !Options.ext_lib [!Options.ext_obj; "cmi"] linker;;

let native_output_obj x = native_link_gen ocamlopt_link_prog
  (fun tags -> tags++"ocaml"++"link"++"native"++"output_obj") x;;

rule "ocaml: cmx* & o* -> native.o"
  ~tags:["ocaml"; "native"; "output_obj" ]
  ~prod:"%.native.o" ~deps:["%.cmx"; "%.o"]
  (native_output_obj "%.cmx" "%.native.o");;


let byte_link_gen = link_gen "cmo" "cma" "cma" ["cmo"; "cmi"];;
let byte_output_obj = byte_link_gen ocamlc_link_prog
  (fun tags -> tags++"ocaml"++"link"++"byte"++"output_obj");;

rule "ocaml: cmo* -> byte.o"
  ~tags:["ocaml"; "byte"; "link"; "output_obj" ]
  ~prod:"%.byte.o" ~dep:"%.cmo"
  (byte_output_obj "%.cmo" "%.byte.o");;
